include ../../def.makefile

MODULE = surfModule

OBJS = surfMain.o surf.o service.o frequencySample.o condInfo.o ring.o \
       spiral.o wire.o rectSpiral.o otherShape.o \
       formulation.o extractZ.o preconditioner.o portCurrent.o superLU.o

include $(UTIL_DIR)/share.cc.makefile









