include ../../../def.makefile

#TEST_FREESPACE = -DTEST_FREESPACE

MODULE = testEikrOverR
#MODULE = testOneOverR
#MODULE = testCalcp

OBJS = element.o utils.o kernelIntegration.o

UTIL_DIR = ../../../util

GDB_FLAG = -g
OPTIM_FLAG =

include $(UTIL_DIR)/shareTest.cc.makefile







